/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package heroSquad;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import spark.ModelAndView;
import spark.template.velocity.VelocityTemplateEngine;
import static spark.Spark.*;

public class App {

    public static void main(String[] args) {
        staticFileLocation("/public");
        String layout = "templates/layout.vtl";

        get("/",(request,response)->{
            Map<String, Object> model = new HashMap<String, Object>();
            model.put("template", "templates/index.vtl");
            return new ModelAndView(model, layout);
        }, new VelocityTemplateEngine());

        get("/heroes/new",(request, response) ->{
            Map<String, Object> model = new HashMap<String, Object>();
            model.put("template", "templates/heroform.vtl");
            return new ModelAndView(model, layout);
        }, new VelocityTemplateEngine());
        get("",(request,response)->{
            Map<String, Object> model = new HashMap<String, Object>();
            model.put("template", "templates/heroList.vtl");
            return new ModelAndView(model, layout);
        }, new VelocityTemplateEngine());
    }
}
